from django.urls import path
from . import views, views_crud

urlpatterns = [
    path("", views.home, name="home"),
    path("api/parse/", views.parse_entry, name="parse_entry"),
    path("api/save/", views.save_entry, name="save_entry"),
    path("expenses/", views_crud.expense_list, name="expense_list"),
    path("expenses/<int:pk>/", views_crud.expense_detail, name="expense_detail"),
    path("expenses/<int:pk>/edit/", views_crud.expense_edit, name="expense_edit"),
    path("expenses/<int:pk>/delete/", views_crud.expense_delete, name="expense_delete"),
    path("tasks/", views_crud.task_list, name="task_list"),
    path("tasks/<int:pk>/", views_crud.task_detail, name="task_detail"),
    path("tasks/<int:pk>/edit/", views_crud.task_edit, name="task_edit"),
    path("tasks/<int:pk>/delete/", views_crud.task_delete, name="task_delete"),
    path("notes/", views_crud.note_list, name="note_list"),
    path("notes/<int:pk>/", views_crud.note_detail, name="note_detail"),
    path("notes/<int:pk>/edit/", views_crud.note_edit, name="note_edit"),
    path("notes/<int:pk>/delete/", views_crud.note_delete, name="note_delete"),
    path("categories/", views_crud.category_list, name="category_list"),
    path("categories/create/", views_crud.category_create, name="category_create"),
    path("categories/<int:pk>/edit/", views_crud.category_edit, name="category_edit"),
    path("categories/<int:pk>/deactivate/", views_crud.category_deactivate, name="category_deactivate"),
    path("budget/", views_crud.budget, name="budget"),
    path("recurring/", views_crud.recurring_list, name="recurring_list"),
    path("recurring/create/", views_crud.recurring_create, name="recurring_create"),
    path("recurring/<int:pk>/edit/", views_crud.recurring_edit, name="recurring_edit"),
    path("recurring/<int:pk>/deactivate/", views_crud.recurring_deactivate, name="recurring_deactivate"),
    path("installments/", views_crud.installment_list, name="installment_list"),
    path("installments/create/", views_crud.installment_create, name="installment_create"),
    path("installments/<int:pk>/edit/", views_crud.installment_edit, name="installment_edit"),
    path("installments/<int:pk>/pay/", views_crud.installment_pay, name="installment_pay"),
]
