# Generated by Django 5.2.17 on 2026-08-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0006_expense_deleted_at_expense_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="category",
            name="unique_category_per_user",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="kind",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="is_default",
            new_name="is_system",
        ),
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(blank=True, help_text="Tailwind or hex color, e.g. #f97316 or orange-500", max_length=20),
        ),
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="type",
            field=models.CharField(choices=[("expense", "支出"), ("income", "收入")], default="expense", max_length=20),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(fields=["user", "name", "type"], name="unique_category_per_user"),
        ),
    ]
