# Generated by Django 5.2.17 on 2026-08-10 05:26

from django.db import migrations

SYSTEM_COLORS = {
    "餐饮": "#f97316",
    "交通": "#3b82f6",
    "住房": "#8b5cf6",
    "生活缴费": "#06b6d4",
    "购物": "#ec4899",
    "其他": "#6b7280",
    "工资": "#22c55e",
    "其他收入": "#a3e635",
}


def apply_colors(apps, schema_editor):
    Category = apps.get_model("life", "Category")
    for name, color in SYSTEM_COLORS.items():
        Category.objects.filter(user__isnull=True, name=name).update(color=color, is_active=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0007_category_v2"),
    ]

    operations = [
        migrations.RunPython(apply_colors, reverse_code=noop),
    ]
