# Generated by Django 5.2.17 on 2026-08-10 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0010_alter_category_options_alter_expense_note_budget"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "每周"),
                            ("monthly", "每月"),
                            ("quarterly", "每季度"),
                            ("yearly", "每年"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "due_day",
                    models.PositiveSmallIntegerField(help_text="Day of month (1-31)"),
                ),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(blank=True, help_text="留空表示无截止日期", null=True),
                ),
                ("remind_days_before", models.PositiveSmallIntegerField(default=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_expenses",
                        to="life.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["is_active", "due_day"],
            },
        ),
    ]
