# Generated by Django 5.2.17 on 2026-08-10 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0011_recurringexpense"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstallmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "installment_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("total_periods", models.PositiveSmallIntegerField()),
                ("paid_periods", models.PositiveSmallIntegerField(default=0)),
                ("next_due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "进行中"),
                            ("completed", "已还清"),
                            ("cancelled", "已取消"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installment_plans",
                        to="life.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installment_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-status", "next_due_date"],
            },
        ),
    ]
