# Generated by Django 5.2.17 on 2026-08-10 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0013_task_v2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("birthday", "生日"),
                            ("bill", "账单"),
                            ("custom", "自定义"),
                            ("task", "任务"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("event_at", models.DateTimeField(help_text="事件发生的日期时间")),
                (
                    "remind_at",
                    models.DateTimeField(help_text="提醒触发时间 = event_at - remind_days"),
                ),
                (
                    "remind_days_before",
                    models.CharField(
                        default="1",
                        help_text="Comma-separated days, e.g. 1,7,15",
                        max_length=50,
                    ),
                ),
                (
                    "recurrence_rule",
                    models.CharField(
                        choices=[
                            ("none", "不重复"),
                            ("daily", "每天"),
                            ("weekly", "每周"),
                            ("monthly", "每月"),
                            ("yearly", "每年"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["remind_at"],
            },
        ),
    ]
