# Generated by Django 5.2.17 on 2026-08-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0014_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="recurrence_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Day of month (1-31) for monthly/yearly",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="recurrence_days_before",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Remind N days before due date"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="recurrence_rule",
            field=models.CharField(
                default="none",
                help_text="none/daily/weekly/monthly/yearly",
                max_length=20,
            ),
        ),
    ]
