# Generated by Django 5.2.17 on 2026-08-10 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0015_task_recurrence_day_task_recurrence_days_before_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_text", models.TextField()),
                (
                    "input_type",
                    models.CharField(
                        choices=[("voice", "语音"), ("text", "文本")],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        help_text="AI model name, e.g. deepseek-v3",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("confirmed", "已确认"),
                            ("cancelled", "已取消"),
                            ("error", "解析失败"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence", models.FloatField(default=0.0, help_text="0.0–1.0")),
                (
                    "draft_json",
                    models.JSONField(default=dict, help_text="Raw AI output as JSON"),
                ),
                ("is_confirmed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parse_results",
                        to="life.conversationlog",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProposedAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create_expense", "新建支出"),
                            ("create_task", "新建任务"),
                            ("create_reminder", "新建提醒"),
                            ("create_note", "新建记事"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(blank=True, max_length=50)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("event_at", models.DateTimeField(blank=True, null=True)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parse_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposed_actions",
                        to="life.parseresult",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
