# Generated by Django 5.2.17 on 2026-08-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0016_conversationlog_parseresult_proposedaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationlog",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Estimated cost in USD",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="conversationlog",
            name="token_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Total tokens used", null=True
            ),
        ),
    ]
