# Generated by Django 5.2.17 on 2026-08-10 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0018_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "evidence",
                    models.TextField(
                        help_text="Data basis for this suggestion, e.g. '餐饮本月 ¥820，比过去3月均值 ¥670 高 22%'"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g. spending/task/reminder/budget",
                        max_length=40,
                    ),
                ),
                (
                    "feedback",
                    models.CharField(
                        blank=True,
                        help_text="useful/not_useful/dismissed",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
    ]
