# Generated by Django 5.2.17 on 2026-08-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0019_suggestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposedaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("create_expense", "新建支出"),
                    ("create_task", "新建任务"),
                    ("create_reminder", "新建提醒"),
                    ("create_note", "新建记事"),
                    ("create_recurring_expense", "新建固定账单"),
                ],
                max_length=30,
            ),
        ),
    ]
