# Generated by Django 5.2.17 on 2026-08-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0020_alter_proposedaction_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="source",
            field=models.CharField(
                choices=[
                    ("voice", "语音"),
                    ("text", "文本"),
                    ("manual", "手动"),
                    ("ai", "AI"),
                    ("rule", "规则"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
