# Generated by Django 5.2.17 on 2026-08-23 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0021_alter_task_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCheckin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "icon",
                    models.CharField(
                        default="📌",
                        help_text="Emoji shown on the home card.",
                        max_length=4,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "reminder_time",
                    models.TimeField(
                        blank=True,
                        help_text="Optional time-of-day the user wants to do it (display only).",
                        null=True,
                    ),
                ),
                (
                    "done_dates",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of ISO date strings (YYYY-MM-DD) when this was checked.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["is_active", "-created_at"],
            },
        ),
    ]
