# Generated by Django 5.2.17 on 2026-08-25 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0023_alter_proposedaction_action_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Countdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("target_date", models.DateField(help_text="目标日期")),
                (
                    "direction",
                    models.CharField(
                        choices=[("down", "倒计时（向目标日期倒数）"), ("up", "纪念日（从过去日期数已经多少天）")],
                        default="down",
                        max_length=8,
                    ),
                ),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("none", "不重复"),
                            ("yearly", "每年"),
                            ("monthly", "每月"),
                            ("weekly", "每周"),
                            ("daily", "每天"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="1-4 chars 可含 emoji",
                        max_length=8,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hex color e.g. #5b8def",
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, max_length=500)),
                (
                    "show_on_home",
                    models.BooleanField(default=True, help_text="是否在首页小板块显示"),
                ),
                (
                    "sync_to_reminder",
                    models.BooleanField(default=False, help_text="同步为日历提醒，提前 N 天提醒"),
                ),
                ("pinned", models.BooleanField(default=False, help_text="首页置顶")),
                ("is_active", models.BooleanField(default=True, help_text="软删除开关")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reminder",
                    models.OneToOneField(
                        blank=True,
                        help_text="已同步的日历提醒（删除 Countdown 时不会级联删除 Reminder）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="countdown",
                        to="life.reminder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="countdowns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["pinned", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active", "target_date"],
                        name="life_countd_user_id_ba1f11_idx",
                    )
                ],
            },
        ),
    ]
