# Generated by Django 5.2.17 on 2026-08-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0024_countdown"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Entry",
        ),
    ]
