# Generated by Django 5.2.17 on 2026-08-27 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0025_delete_entry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["user", "month"], name="life_budget_user_id_fa83c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["user", "category"], name="life_budget_user_id_6b3a67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationlog",
            index=models.Index(
                fields=["user", "created_at"], name="life_conver_user_id_98a75e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["user", "is_deleted", "occurred_at"],
                name="life_expens_user_id_f6101e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["user", "is_deleted", "type", "status"],
                name="life_expens_user_id_e756e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["user", "is_deleted", "category"],
                name="life_expens_user_id_d94805_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="installmentplan",
            index=models.Index(
                fields=["user", "status"], name="life_instal_user_id_f98438_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["user", "is_deleted", "created_at"],
                name="life_note_user_id_d58e5b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["user", "is_deleted", "occurred_on"],
                name="life_note_user_id_f86d8e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recurringexpense",
            index=models.Index(
                fields=["user", "is_active"], name="life_recurr_user_id_187a8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reminder",
            index=models.Index(
                fields=["user", "is_enabled", "remind_at"],
                name="life_remind_user_id_a8093b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reminder",
            index=models.Index(
                fields=["user", "is_enabled", "event_at"],
                name="life_remind_user_id_f8e13d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["user", "period_start"], name="life_review_user_id_08ecf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["user", "is_deleted", "due_at"],
                name="life_task_user_id_5a106c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["user", "is_deleted", "status"],
                name="life_task_user_id_91884a_idx",
            ),
        ),
    ]
