# Generated by Django 5.2.17 on 2026-08-27 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0026_add_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParseJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        default="97a18ef006834665b201baeea467bd13",
                        help_text="对外暴露的任务标识，用于轮询，无业务含义",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("raw_text", models.TextField(help_text="待解析的原始文本")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "解析中"),
                            ("done", "已完成"),
                            ("error", "失败"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, help_text="解析结果（与 route_parse 返回结构一致）", null=True
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parse_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "-created_at"],
                        name="parsejob_user_status_idx",
                    )
                ],
            },
        ),
    ]
