# Generated by Django 5.2.17 on 2026-08-29 05:37

import life.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0027_parsejob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parsejob",
            name="uuid",
            field=models.CharField(
                db_index=True,
                default=life.models._default_parse_job_uuid,
                help_text="对外暴露的任务标识，用于轮询，无业务含义",
                max_length=32,
                unique=True,
            ),
        ),
    ]
