# Generated by Django 5.2.17 on 2026-08-29 15:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0029_tag_expense_tags_note_tags_task_tags_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cash", "现金"),
                            ("bank", "银行卡"),
                            ("alipay", "支付宝"),
                            ("wechat", "微信"),
                            ("credit", "信用卡"),
                            ("other", "其他"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, help_text="留空则用类型默认图标", max_length=8),
                ),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="启用时的初始余额；之后由流水推算",
                        max_digits=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_active", "type", "name"],
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="资金变动的账户：支出时从该账户扣减，收入时计入该账户",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="life.account",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="transfer_to_account",
            field=models.ForeignKey(
                blank=True,
                help_text="仅 type=transfer 时有值：转入的目标账户",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incoming_transfers",
                to="life.account",
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["user", "is_deleted", "is_active"],
                name="life_accoun_user_id_cb9d19_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_account_per_user"
            ),
        ),
    ]
