# Generated by Django 5.2.17 on 2026-08-30 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0030_account_expense_account_expense_transfer_to_account_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(help_text="对应 BADGE_DEFS 中的 key", max_length=40),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "key"], name="life_badge_user_id_cef956_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "key"), name="unique_badge_per_user"
                    )
                ],
            },
        ),
    ]
