# Generated by Django 5.2.17 on 2026-08-30 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0031_badge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="important",
            field=models.BooleanField(
                default=False, help_text="四象限：重要性（对标滴答清单 Eisenhower）"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="urgent",
            field=models.BooleanField(default=False, help_text="四象限：紧急性"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["user", "is_deleted", "important", "urgent"],
                name="life_task_user_id_75518c_idx",
            ),
        ),
    ]
