# Generated by Django 5.2.17 on 2026-08-30 07:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0032_task_important_task_urgent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavingsGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="🎯",
                        help_text="1-4 chars 可含 emoji",
                        max_length=8,
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True, help_text="目标达成期限（留空表示无期限）", null=True
                    ),
                ),
                ("note", models.TextField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True, help_text="软删除开关")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savings_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="life_saving_user_id_7b67d5_idx",
                    )
                ],
            },
        ),
    ]
