# Generated by Django 5.2.17 on 2026-08-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0034_balance_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringexpense",
            name="auto_post",
            field=models.BooleanField(default=True, help_text="到期自动生成一笔账目（关闭后仅提醒）"),
        ),
        migrations.AddField(
            model_name="recurringexpense",
            name="last_generated_date",
            field=models.DateField(
                blank=True, help_text="已自动生成账目的截止日期（幂等游标）", null=True
            ),
        ),
    ]
