# Generated by Django 5.2.17 on 2026-08-30 16:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0037_category_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="currency",
            field=models.CharField(
                choices=[
                    ("CNY", "人民币 (CNY)"),
                    ("USD", "美元 (USD)"),
                    ("HKD", "港币 (HKD)"),
                    ("TWD", "新台币 (TWD)"),
                    ("JPY", "日元 (JPY)"),
                    ("EUR", "欧元 (EUR)"),
                    ("GBP", "英镑 (GBP)"),
                    ("KRW", "韩元 (KRW)"),
                    ("SGD", "新加坡元 (SGD)"),
                    ("AUD", "澳元 (AUD)"),
                    ("THB", "泰铢 (THB)"),
                    ("MYR", "马来西亚林吉特 (MYR)"),
                ],
                default="CNY",
                help_text="账户币种；本位币为 CNY",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="amount_base",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="折算后的本位币金额（保存时自动计算）",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="currency",
            field=models.CharField(
                choices=[
                    ("CNY", "人民币 (CNY)"),
                    ("USD", "美元 (USD)"),
                    ("HKD", "港币 (HKD)"),
                    ("TWD", "新台币 (TWD)"),
                    ("JPY", "日元 (JPY)"),
                    ("EUR", "欧元 (EUR)"),
                    ("GBP", "英镑 (GBP)"),
                    ("KRW", "韩元 (KRW)"),
                    ("SGD", "新加坡元 (SGD)"),
                    ("AUD", "澳元 (AUD)"),
                    ("THB", "泰铢 (THB)"),
                    ("MYR", "马来西亚林吉特 (MYR)"),
                ],
                default="CNY",
                help_text="记账币种；本位币为 CNY，非本位币可填汇率折算",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="rate",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("1"),
                help_text="1 单位本币 = rate 单位本位币（CNY）；手工填写，默认 1",
                max_digits=12,
            ),
        ),
    ]
