# Generated by Django 5.2.17 on 2026-08-09 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("expense.create", "创建支出"),
                            ("expense.update", "修改支出"),
                            ("expense.delete", "删除支出"),
                            ("task.create", "创建待办"),
                            ("task.update", "修改待办"),
                            ("task.complete", "完成待办"),
                            ("task.delete", "删除待办"),
                            ("note.create", "创建随心记"),
                            ("note.update", "修改随心记"),
                            ("note.delete", "删除随心记"),
                            ("login.failed", "登录失败"),
                            ("ai.save", "AI 解析确认保存"),
                        ],
                        max_length=40,
                    ),
                ),
                ("target_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("summary", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
