# Generated by Django 5.2.17 on 2026-08-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_pushsubscription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="email_last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="email_retry_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
