# Generated by Django 5.2.17 on 2026-08-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="daily_ai_limit",
            field=models.PositiveSmallIntegerField(
                default=20, help_text="单日 AI 调用上限，0=不限制"
            ),
        ),
    ]
