# Generated by Django 5.2.17 on 2026-08-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_daily_ai_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_important_only",
            field=models.BooleanField(default=True, help_text="仅发送重要提醒（优先级=高）"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_notifications",
            field=models.BooleanField(default=False, help_text="启用邮件提醒"),
        ),
    ]
