# Generated by Django 5.2.17 on 2026-08-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_email_important_only_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="daily_ai_limit",
            field=models.PositiveSmallIntegerField(
                default=100, help_text="单日 AI 调用上限，0=不限制"
            ),
        ),
    ]
