# Generated by Django 5.2.17 on 2026-08-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_userprofile_daily_ai_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_change_count",
            field=models.PositiveSmallIntegerField(default=0, help_text="邮箱修改次数（上限 3）"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True, help_text="手机号（仅自己可见，可选）", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_change_count",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="手机号修改次数（上限 3）"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="username_change_count",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="用户名修改次数（上限 3）"
            ),
        ),
    ]
