# Generated by Django 5.2.17 on 2026-08-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile_email_change_count_userprofile_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="default_reminder_time",
            field=models.TimeField(
                default="10:00", help_text="语音解析任务/提醒未指定时刻时的默认时间（默认 10:00）"
            ),
        ),
    ]
