# Generated by Django 5.2.17 on 2026-08-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_userprofile_default_reminder_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="当前头像（最大 2MB，推荐 256×256+ PNG/JPG/WebP）",
                null=True,
                upload_to="avatars/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_history",
            field=models.JSONField(
                blank=True, default=list, help_text="历史头像 URL 列表，上限 8 张"
            ),
        ),
    ]
