# Generated by Django 5.2.17 on 2026-08-29 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_userprofile_avatar_userprofile_avatar_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="default_reminder_time",
            field=models.TimeField(
                default=datetime.time(10, 0), help_text="语音解析任务/提醒未指定时刻时的默认时间（默认 10:00）"
            ),
        ),
    ]
