# Generated by Django 5.2.17 on 2026-08-30 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_userprofile_default_reminder_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="daily_log_reminder_enabled",
            field=models.BooleanField(
                default=False, help_text="每日记账提醒：当天没记账时首页提示，并生成每日提醒"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_log_reminder_time",
            field=models.TimeField(
                default=datetime.time(21, 0), help_text="每日记账提醒的提醒时间（默认 21:00）"
            ),
        ),
    ]
